# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtgamma_once <- function(shape, rate, lb, ub) {
    .Call('FDRreg_rtgamma_once', PACKAGE = 'FDRreg', shape, rate, lb, ub)
}

rdirichlet_once <- function(alpha) {
    .Call('FDRreg_rdirichlet_once', PACKAGE = 'FDRreg', alpha)
}

FDRregCPP <- function(z, X, M0, MTot, PriorPrecision, PriorMean, nmc, nburn, p0, betaguess) {
    .Call('FDRreg_FDRregCPP', PACKAGE = 'FDRreg', z, X, M0, MTot, PriorPrecision, PriorMean, nmc, nburn, p0, betaguess)
}

EmpiricalBayesFDRregCPP <- function(z, X, M0, M1, PriorPrecision, PriorMean, nmc, nburn, betaguess) {
    .Call('FDRreg_EmpiricalBayesFDRregCPP', PACKAGE = 'FDRreg', z, X, M0, M1, PriorPrecision, PriorMean, nmc, nburn, betaguess)
}

FullyBayesFDRregCPP <- function(z, X, M0, M1, PriorPrecision, PriorMean, nmc, nburn, betaguess) {
    .Call('FDRreg_FullyBayesFDRregCPP', PACKAGE = 'FDRreg', z, X, M0, M1, PriorPrecision, PriorMean, nmc, nburn, betaguess)
}

mysample <- function(probs) {
    .Call('FDRreg_mysample', PACKAGE = 'FDRreg', probs)
}

trapezoid <- function(x, y) {
    .Call('FDRreg_trapezoid', PACKAGE = 'FDRreg', x, y)
}

dnormix <- function(y, weights, mu, tau2) {
    .Call('FDRreg_dnormix', PACKAGE = 'FDRreg', y, weights, mu, tau2)
}

marnormix <- function(y, sigma2, weights, mu, tau2) {
    .Call('FDRreg_marnormix', PACKAGE = 'FDRreg', y, sigma2, weights, mu, tau2)
}

rnormix <- function(n, weights, mu, tau2) {
    .Call('FDRreg_rnormix', PACKAGE = 'FDRreg', n, weights, mu, tau2)
}

draw_mixture_component <- function(y, sigma2, weights, mu, tau2) {
    .Call('FDRreg_draw_mixture_component', PACKAGE = 'FDRreg', y, sigma2, weights, mu, tau2)
}

PredictiveRecursionFDR <- function(z, grid_x, theta_guess, nullprob = 0.95, mu0 = 0.0, sig0 = 1.0, decay = -0.67) {
    .Call('FDRreg_PredictiveRecursionFDR', PACKAGE = 'FDRreg', z, grid_x, theta_guess, nullprob, mu0, sig0, decay)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('FDRreg_RcppExport_registerCCallable', PACKAGE = 'FDRreg')
})
